services:

  postgres:
    image: postgres:17
    container_name: business_db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: business_information

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: sales_agent_api
    restart: always

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/business_information
      CHECKPOINTER_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/business_information
      OPENAI_API_KEY: ${OPENAI_API_KEY}

    depends_on:
      - postgres

    volumes:
      - .:/app

volumes:
  postgres_data: